### ISSUE TITLE
passkey in config.yml should be named accounceurl

### ISSUE THREAD

**Issue by newadventure079** [kannibalox/PtpUploader#11]
I believe the passkey setting in the config.yml is looking for the announce url.  Isn't a passkey different than a announce url?  I think that variable should be renamed

**Comment by kannibalox** [comment]
Yeah, I've been going back and forth on that, the passkey is [part of the announce URL](https://github.com/kannibalox/PtpUploader/blob/main/src/PtpUploader/Ptp.py#L23) so the terminology is somewhat interchangeable. I'll change it to `announce_url` since that seems to be the more familiar term.
