### ISSUE TITLE
Request to increase the number of screens to 6

### ISSUE THREAD

**Issue by newadventure079** [kannibalox/PtpUploader#14]
I use this tool to upload to other sites too since it's so damn handy.  Some of the other sites require 6 screens so my request is to bump the number of screens taken to 6.  I know PTP doesn't require 6, but this will also help out if one of the screens is bad and give the PTP uploader more screens to choose from

Changes proposed:

`numberOfScreenshotsToTake=6`

```
if numberOfScreenshotsToTake > 6:
            numberOfScreenshotsToTake = 6
```

**Comment by kannibalox** [comment]
I don't plan to support any other sites, but it was simple enough to make it configurable: https://github.com/kannibalox/PtpUploader/commit/b9239a9cdb6749cfb4658c6d5271c65e82e16b91
