### ISSUE TITLE
docker run

### ISSUE THREAD

**Issue by daomengRen** [kannibalox/PtpUploader#15]
error:
> dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'ANNOUNCE_URL'"
How should I go to the config file to add this attribute

**Comment by kannibalox** [comment]
the `passkey` config file entry was recently moved to `announce_url` in the config file: https://github.com/kannibalox/PtpUploader/blob/main/src/PtpUploader/config.default.yml#L8, try changing that.
