### ISSUE TITLE
hook

### ISSUE THREAD

**Issue by daomengRen** [kannibalox/PtpUploader#16]
> hook:
  on_upload:

could you please add an example for this, I don't know how to use it,thanks

**Comment by kannibalox** [comment]
i've added an example here: https://github.com/kannibalox/PtpUploader/blob/main/src/PtpUploader/config.default.yml#L114, give it a shot

**Comment by daomengRen** [comment]
does this mean that I can also execute bash or python scripts, also for the available fields, can you give a list, I didn't find the UploadedTorrentUrl field in ReleaseInfo.py

**Comment by kannibalox** [comment]
`UploadedTorrentUrl` is the only outlier (it's just there for convenience), everything else is taken directly from ReleaseInfo.py. The command gets sent `/bin/sh`, which means you can run pretty much anything you have permissions to.

**Comment by daomengRen** [comment]
the properties under each class of ReleaseInfo.py are available fields, is that what I think

**Comment by kannibalox** [comment]
Correct, sorry if that wasn't clear.

**Comment by daomengRen** [comment]
It's ok, I'll try each one more, thanks a lot
