### ISSUE TITLE
Feature: blu-ray support

### ISSUE THREAD

**Issue by kannibalox** [kannibalox/PtpUploader#19]
The main blocker is BDinfo being a pain to get working. There are repos such as https://github.com/L4GSP1KE/Upload-Assistant that directly embed binaries, but that's hopefully a last resort.

**Comment by daomengRen** [comment]
https://github.com/zoffline/BDInfoCLI-ng
hope this will help you

**Comment by leonard4546** [comment]
I use https://github.com/Aniverse/bluray/blob/master/bluray to get bdinfo on linux cli

Example: https://files.catbox.moe/rb80ue.png

**Comment by kannibalox** [comment]
Added experimental support based on zoffline/BDInfoCLI-ng in bff8752. The bdinfo path can take a command with spaces, e.g. `path: mono /tmp/BDInfo/build/BDInfo.exe`  is what I've been testing with.

**Comment by kannibalox** [comment]
Implemented in https://github.com/kannibalox/PtpUploader/releases/tag/v0.10.0, I've done some testing but feel free to open another ticket if you find any issues.
