### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by daomengRen** [kannibalox/PtpUploader#5]
There was an error in docker build, it seems that no matching version was found, how can I fix it, thank you
log:
_ERROR: Could not find a version that satisfies the requirement imdbpy (unavailable) (from ptpuploader) (from versions: 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.8.1, 4.8.2, 4.9, 5.0, 5.1.1, 6.0, 6.2, 6.3, 6.4, 6.4.1, 6.5, 6.6, 6.7, 6.8, 2020.9.25, 2021.4.18)  ERROR: No matching distribution found for imdbpy (unavailable)_

**Comment by kannibalox** [comment]
That's very strange, imdbpy should be installing directly from git. Can you try again with the latest version of the Dockerfile for me?

**Comment by daomengRen** [comment]
It's very strange, I have this error on one computer, but not on the other, I don't know if there is this problem

**Comment by daomengRen** [comment]
I'll close it, and if I find a problem, I'll open
