### ISSUE TITLE
Conflicting info about which python version is supported

### ISSUE THREAD

**Issue by newadventure079** [kannibalox/PtpUploader#6]
The readme says `Most importantly, only python 3+ is supported`, whereas install.md says `Only version 2.7 is supported (earlier versions may work, but no support is provided for them).`  Install.md also refers to `pip` instead of `pip3`

**Comment by kannibalox** [comment]
Yep, sorry, I'm in the middle of rewriting the documentation so a bunch of things are in flux. Python 3 (3.7+ specifically I believe, need to go back and double check that) is the supported version. A lot of systems have pip always pointing to the most recently installed version of python, but you're correct that the documentation should be more specific.

I'll put out an actual github release once things are in a stable state.

**Comment by newadventure079** [comment]
I appreciate it.  Looking forward to it!

**Comment by kannibalox** [comment]
Everything should at least be consistent now, so closing this

**Comment by newadventure079** [comment]
@kannibalox 

On `https://github.com/kannibalox/PtpUploader/blob/main/INSTALL.md` it says `# source /.local/ptpuploader/bin/activate` but at the main readme it says `virtualenv ~/.venv/ptpuploader/`

So the line about `~/.local` needs to be updated to `~/.venv` to match the new venv instructions

**Comment by kannibalox** [comment]
Good catch, fixed
